[package]
name = "async-hwi"
version = "0.0.9"
edition = "2018"
description = "Async hardware wallet interface"
authors = ["Edouard Paris <m@edouard.paris>"]
license-file = "LICENSE"
repository = "https://github.com/revault/async-hwi"
keywords = ["bitcoin"]

[features]
default = ["ledger", "specter", "trezor"]
trezor = ["trezor-client"]
specter = ["tokio", "tokio-serial", "serialport"]
ledger = ["regex", "tokio", "ledger_bitcoin_client", "ledger-apdu", "ledger-transport-hid", "hidapi"]

[dependencies]
base64 = "0.13.0"
async-trait = "0.1.52"
futures = "0.3"
bitcoin = { version = "0.30.0", default-features = false, features = ["base64", "serde", "no-std"] }

# specter & ledger
tokio = { version = "1.21.0", features = ["net", "time", "io-util", "sync"], optional = true }

# specter
tokio-serial = { version = "5.4.1", optional = true }
serialport = { version = "4.2", optional = true }

# ledger
regex = { version = "1.6.0", optional = true }
ledger_bitcoin_client = { version = "0.3.1", optional = true }
ledger-apdu = { version = "0.10", optional = true }
ledger-transport-hid = { version = "0.10", optional = true }
hidapi = { version = "1.4.1", features = ["linux-static-hidraw"], default-features = false, optional = true }

# trezor
trezor-client = { version = "0.1.2", optional = true }

[dev-dependencies]
tokio = { version = "1.21", features = ["macros", "net", "rt", "rt-multi-thread", "io-util", "sync"] }
